apiVersion: v1
kind: Service
metadata:
  name: flink-taskmanager
spec:
  type: ClusterIP
  ports:
  - name: rpc
    port: 6122
  - name: query-state
    port: 6125
  selector:
    app: flink
    component: taskmanager